### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# File to Load (Remember to Change These)
file_to_load = "Resources/purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
purchase_data = pd.read_csv(file_to_load)

In [2]:
purchase_data.head()

Purchase ID             SN  Age Gender  Item ID  \
0            0        Lisim78   20   Male      108   
1            1    Lisovynya38   40   Male      143   
2            2     Ithergue48   24   Male       92   
3            3  Chamassasya86   24   Male      100   
4            4      Iskosia90   23   Male      131   

                                   Item Name  Price  
0  Extraction, Quickblade Of Trembling Hands   3.53  
1                          Frenzied Scimitar   1.56  
2                               Final Critic   4.88  
3                                Blindscythe   3.27  
4                                       Fury   1.44

In [3]:
IDs = np.unique(purchase_data["SN"])

In [4]:
players = len(IDs)

## Player Count

* Display the total number of players


In [5]:
print(players)

576


## Purchasing Analysis (Total)

In [6]:
items = np.unique(purchase_data["Item ID"])
avgprice = np.mean(purchase_data["Price"])
purchasecount = len(purchase_data["Purchase ID"])
revenue = np.sum(purchase_data["Price"])
print(len(items), avgprice, purchasecount, revenue)

183 3.050987179487176 780 2379.77


In [9]:
df = pd.DataFrame(
    {"Number of Unique Items": [len(items)],
     "Average Price": ["$"+str(np.round(avgprice,2))], "Number of Purchases": [purchasecount], "Total Revenue": ["$"+str(revenue)]
     }
)

             
                  
                  

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame


In [ ]:
df.style.set_table_styles(styles)

In [10]:
df

Number of Unique Items Average Price  Number of Purchases Total Revenue
0                     183         $3.05                  780      $2379.77

## Gender Demographics

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed




In [12]:
gender_types = np.unique(purchase_data["Gender"])
print(gender_types)

['Female' 'Male' 'Other / Non-Disclosed']


In [13]:
from collections import Counter


In [14]:
uniq_plr=np.unique(purchase_data["SN"],return_index=True)


In [16]:
indices_of_uniq_pl = uniq_plr[1]


In [17]:
pl_dat=Counter(purchase_data["Gender"][uniq_plr[1]])

In [18]:
pl_dat_values=list(pl_dat.values())
pl_dat_keys = list(pl_dat.keys())

In [19]:
print(pl_dat_keys)

['Male', 'Female', 'Other / Non-Disclosed']


In [20]:
df = pd.DataFrame(
    {"Number of Unique Items": [len(items)],
     "Average Price": [np.round(avgprice,2)], "Number of Purchases": [purchasecount], "Total Revenue": [revenue]
     }
)

In [21]:
df1 = pd.DataFrame(
    {"Gender": [i for i in pl_dat_keys], 
     "Total Count":[j for j in pl_dat_values],
     "Percentage of Players": [str(np.round(100*k/players,2))+"%" for k in pl_dat_values]
    }
)


In [22]:
td_props = [
  ('font-size', '11px')
  ]

# Set table styles
styles = [
  
  dict(selector="td", props=td_props)
  ]


In [23]:
df1.style.set_table_styles(styles)

In [24]:
#I accidentally deleted the example dataframe


## Purchasing Analysis (Gender)

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [25]:
genderlist = np.array(purchase_data["Gender"])

In [26]:
male_ind= np.where(genderlist=="Male")[0]
fml_ind =np.where(genderlist=="Female")[0]
tbt_ind = np.where(genderlist==pl_dat_keys[2])[0]
#len of each array is the first column of purchase count 

In [27]:
len(male_ind)

652

In [28]:
tpv_m=np.sum(np.array(purchase_data["Price"])[male_ind])
tpv_f=np.sum(np.array(purchase_data["Price"])[fml_ind])
tpv_o=np.sum(np.array(purchase_data["Price"])[tbt_ind])
#sum of each array is the total purchase value


In [29]:
app_m=np.mean(np.array(purchase_data["Price"])[male_ind])
app_f=np.mean(np.array(purchase_data["Price"])[fml_ind])
app_o=np.mean(np.array(purchase_data["Price"])[tbt_ind])
#mean of each array is the average purchase price


In [30]:
male_sn_list = np.array(purchase_data["SN"])[male_ind]
male_sn_ul=np.unique(male_sn_list)
male_purc_list = np.zeros(len(male_sn_ul))
for i in range(0,len(male_sn_ul)):
    male_purc_list[i]= np.sum(np.array(purchase_data["Price"])
                              [np.where(np.array(purchase_data["SN"])== male_sn_ul[i])[0]])


In [31]:
fml_sn_list =np.array(purchase_data["SN"])[fml_ind]
fml_sn_ul=np.unique(fml_sn_list)
fml_purc_list=np.zeros(len(fml_sn_ul))
for i in range(0,len(fml_sn_ul)):
    fml_purc_list[i]=np.sum(np.array(purchase_data["Price"])[np.where(np.array(purchase_data["SN"])==fml_sn_ul[i])[0]])

In [32]:
tbt_sn_list =np.array(purchase_data["SN"])[tbt_ind]
tbt_sn_ul=np.unique(tbt_sn_list)
tbt_purc_list=np.zeros(len(tbt_sn_ul))
for i in range(0,len(tbt_sn_ul)):
    tbt_purc_list[i]=np.sum(np.array(purchase_data["Price"])[np.where(np.array(purchase_data["SN"])==tbt_sn_ul[i])[0]])


In [33]:
np.mean(fml_purc_list)

4.468395061728395

In [34]:
np.sum(fml_purc_list)

361.94

In [35]:
np.mean(male_purc_list)


4.065371900826446

In [38]:
np.mean(tbt_purc_list)


4.5627272727272725

In [39]:
data = [["Female", len(fml_ind), "$"+str(np.round(app_f,2)), "$"+str(tpv_f), "$"+str(np.round(np.mean(fml_purc_list),2))],
["Male", len(male_ind), "$"+str(np.round(app_m,2)), "$"+str(tpv_m), "$"+str(np.round(np.mean(male_purc_list),2))],
["Other/Non-Disclosed", len(tbt_ind), "$"+str(np.round(app_o,2)), "$"+str(tpv_o), "$"+str(np.round(np.mean(tbt_purc_list),2))]]

In [40]:
df3 = pd.DataFrame(data, columns = ["Gender", "Purchase Count", "Average Purchase Price", "Total Purchase Value", "Average Total Purchase Per Person"])

In [41]:
df3


Gender  Purchase Count Average Purchase Price  \
0               Female             113                   $3.2   
1                 Male             652                  $3.02   
2  Other/Non-Disclosed              15                  $3.35   

  Total Purchase Value Average Total Purchase Per Person  
0              $361.94                             $4.47  
1             $1967.64                             $4.07  
2               $50.19                             $4.56

In [42]:
#I accidentally deleted the example dataframe


## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table


In [43]:
bins = [0,9,14,19,24,29,34,39,100]


In [44]:
intervals = ["<10", "10-14","15-19","20-24","25-29","30-34","35-39","40+"]

In [115]:
df5= pd.cut(purchase_data["Age"][uniq_plr[1]], bins, labels=intervals)
#purchase_data["Age"][uniq_plr[1]]--> tells me the ages of ALL THE UNIQUE USERS
total_age_counts=df5.value_counts()

In [116]:
df6 =pd.DataFrame({"Interval":[i for i in intervals],
                   "Total Count":[df5.value_counts()[j] for j in range(0,len(df5.value_counts()))],
                   "Percentage of Players": [str(percentage[k])+"%" for k in range(0,len(percentage))]
                  })
                   
    




In [117]:
df6

Interval  Total Count Percentage of Players
0      <10           17                 3.82%
1    10-14           22                18.58%
2    15-19          107                44.79%
3    20-24          258                13.37%
4    25-29           77                 9.03%
5    30-34           52                 5.38%
6    35-39           31                 2.08%
7      40+           12                 2.95%

In [48]:
bin_un=np.unique(df5)
count_age =np.zeros(len(bin_un))

In [49]:
for i in range (0,len(bin_un)):
    
    count_age[i]=len(np.where(df5==bin_un[i])[0])

In [50]:
print(count_age)


[ 22. 107. 258.  77.  52.  31.  12.  17.]


In [56]:
percentage = np.round(100*count_age/len(uniq_plr[1]),2)
print(percentage)

[ 3.82 18.58 44.79 13.37  9.03  5.38  2.08  2.95]


## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [241]:
df7= pd.cut(purchase_data["Age"], bins, labels=intervals)
#bin ALL THE Transcations according age of the users (not unique users!!!)
age_dem=df7.value_counts()
#age demographics
age_dem[0]

23

In [105]:
ind = np.digitize(purchase_data["Age"], bins,right=True)
unt = np.unique(ind)
unt

array([1, 2, 3, 4, 5, 6, 7, 8])

In [109]:
indices = np.where(ind==unt[7])[0]
to=np.sum(purchase_data["Price"][indices])
print(to)

38.24


In [152]:
total_purch_anal=np.zeros(len(unt))
av_purch_pr= np.zeros(len(unt))
avg_total_ppp=np.zeros(len(unt))

In [153]:

for i in  range(0,len(unt)):
    indices = np.where(ind==unt[i])[0]
    total_purch_anal[i]=np.sum(purchase_data["Price"][indices])
    
    

In [242]:
for i in  range(0,len(unt)):
    av_purch_pr[i]=total_purch_anal[i]/age_dem[i]

In [239]:
for i in  range(0,len(unt)):
    avg_total_ppp[i]=total_purch_anal[i]/total_age_counts[i]

In [243]:
av_purch_pr

array([3.35347826, 2.95642857, 3.03595588, 3.05221918, 2.9009901 ,
       2.93150685, 3.60170732, 2.94153846])

In [244]:
df8=pd.DataFrame({"Age Ranges":[i for i in intervals], 
                  "Purchase Count":[age_dem[j] for j in range(0,len(age_dem))],
                 "Average Purchase Price":[k for k in av_purch_pr],
                 "Total Purchase Price":[l for l in total_purch_anal],
                 "Average Total Purchase Per person":[t for t in avg_total_ppp]
                 })

In [245]:
df8

Age Ranges  Purchase Count  Average Purchase Price  Total Purchase Price  \
0        <10              23                3.353478                 77.13   
1      10-14              28                2.956429                 82.78   
2      15-19             136                3.035956                412.89   
3      20-24             365                3.052219               1114.06   
4      25-29             101                2.900990                293.00   
5      30-34              73                2.931507                214.00   
6      35-39              41                3.601707                147.67   
7        40+              13                2.941538                 38.24   

   Average Total Purchase Per person  
0                           4.537059  
1                           3.762727  
2                           3.858785  
3                           4.318062  
4                           3.805195  
5                           4.115385  
6                           4.763548  
7                           3.186667

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame



In [250]:
sn_purch=np.zeros(len(uniq_plr[0]))
for i in range(0, len(uniq_plr[0])):
    ind_sn=np.where(purchase_data["SN"]==uniq_plr[0][i])[0]
    sn_purch[i]=np.sum(purchase_data["Price"][ind_sn])

In [251]:
#find the indices of the 5 largest values in the list (sn_purch)
idx = (-sn_purch).argsort()[:5]

top_player=uniq_plr[0][idx]

print(top_player,sn_purch[idx])


['Lisosia93' 'Idastidru52' 'Chamjask73' 'Iral74' 'Iskadarya95'] [18.96 15.45 13.83 13.62 13.1 ]


In [252]:
num_occur=np.zeros(len(top_player))
for i in range(0,len(top_player)):
    num_occur[i]=len(np.where(purchase_data["SN"]==top_player[i])[0])
    
print(num_occur)


[5. 4. 3. 4. 3.]


In [253]:
av_pur_pr=np.divide(sn_purch[idx],num_occur)

In [254]:
df9= pd.DataFrame({"SN":[i for i in top_player],
                   "Purchase Count":[j for j in num_occur],
                   "Average Purchase Price":[k for k in av_pur_pr],
                   "Total Purchase Value":[g for g in sn_purch[idx]]
    
})

In [255]:
df9

SN  Purchase Count  Average Purchase Price  Total Purchase Value
0    Lisosia93             5.0                3.792000                 18.96
1  Idastidru52             4.0                3.862500                 15.45
2   Chamjask73             3.0                4.610000                 13.83
3       Iral74             4.0                3.405000                 13.62
4  Iskadarya95             3.0                4.366667                 13.10

Purchase Count Average Purchase Price Total Purchase Value
SN                                                                     
Lisosia93                 5                  $3.79               $18.96
Idastidru52               4                  $3.86               $15.45
Chamjask73                3                  $4.61               $13.83
Iral74                    4                  $3.40               $13.62
Iskadarya95               3                  $4.37               $13.10

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame



In [260]:
uniq_item=np.unique(purchase_data["Item ID"])
item_purch=np.zeros(len(uniq_item))
for i in range(0, len(uniq_item)):
    ind_item=np.where(purchase_data["Item ID"]==purchase_data["Item ID"][uniq_item[i]])[0]
    item_purch[i]=len(ind_item)
    
print(item_purch)

[ 9.  6.  8.  5.  5.  2.  4.  5.  5.  6.  3.  5.  4.  5.  4.  5.  6.  5.
  9.  3.  4.  2.  5.  3.  7. 12.  7.  6.  3.  8.  5.  6.  5.  5.  6.  7.
  5.  4.  4.  6.  7.  8.  4.  4.  5.  6.  4.  5.  7.  6.  5.  8.  2.  6.
  3.  9.  5.  4.  4.  5. 12. 12.  2.  2.  8.  2.  5.  1.  8.  6.  5. 12.
  4.  3.  4.  5.  5.  4.  5.  4.  4.  6.  6.  8.  2.  6.  3.  9.  4.  8.
  8.  5.  5.  6.  7.  2.  1.  7.  5.  6.  4.  3.  7.  7.  4.  6.  4.  7.
  2.  5.  3.  7.  5.  5.  4.  5.  7.  7.  5.  5.  3.  4.  2.  5.  3.  8.
  6.  4.  3.  6.  3.  9.  4.  6.  5.  4.  6.  6.  2.  3.  8.  3.  4.  6.
  5.  5.  5.  3.  5.  4.  4.  7.  7.  8.  5.  7.  9.  4.  5.  5.  6.  5.
  5.  6.  3.  2.  4.  7.  4.  8.  6.  5.  4.  6.  8.  4.  3.  4.  8.  3.
  1.  4.  5.]


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

Purchase Count  \
Item ID Item Name                                                     
178     Oathbreaker, Last Hope of the Breaking Storm             12   
145     Fiery Glass Crusader                                      9   
108     Extraction, Quickblade Of Trembling Hands                 9   
82      Nirvana                                                   9   
19      Pursuit, Cudgel of Necromancy                             8   

                                                     Item Price  \
Item ID Item Name                                                 
178     Oathbreaker, Last Hope of the Breaking Storm      $4.23   
145     Fiery Glass Crusader                              $4.58   
108     Extraction, Quickblade Of Trembling Hands         $3.53   
82      Nirvana                                           $4.90   
19      Pursuit, Cudgel of Necromancy                     $1.02   

                                                     Total Purchase Value  
Item ID Item Name                                                          
178     Oathbreaker, Last Hope of the Breaking Storm               $50.76  
145     Fiery Glass Crusader                                       $41.22  
108     Extraction, Quickblade Of Trembling Hands                  $31.77  
82      Nirvana                                                    $44.10  
19      Pursuit, Cudgel of Necromancy                               $8.16

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame



Purchase Count  \
Item ID Item Name                                                     
178     Oathbreaker, Last Hope of the Breaking Storm             12   
82      Nirvana                                                   9   
145     Fiery Glass Crusader                                      9   
92      Final Critic                                              8   
103     Singed Scalpel                                            8   

                                                     Item Price  \
Item ID Item Name                                                 
178     Oathbreaker, Last Hope of the Breaking Storm      $4.23   
82      Nirvana                                           $4.90   
145     Fiery Glass Crusader                              $4.58   
92      Final Critic                                      $4.88   
103     Singed Scalpel                                    $4.35   

                                                     Total Purchase Value  
Item ID Item Name                                                          
178     Oathbreaker, Last Hope of the Breaking Storm               $50.76  
82      Nirvana                                                    $44.10  
145     Fiery Glass Crusader                                       $41.22  
92      Final Critic                                               $39.04  
103     Singed Scalpel                                             $34.80